version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "3"
        NODE_VERSION: "none"
    volumes:
      - .:/workspace:cached
    command: ["/bin/bash", "/usr/local/bin/entrypoint.sh", "sleep", "infinity"]
    network_mode: service:db
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    hostname: postgres
    environment:
      POSTGRES_DB: my_media
      POSTGRES_USER: example
      POSTGRES_PASSWORD: pass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432

volumes:
  postgres-data: null

app:
  build:
    context: ..
    dockerfile: .devcontainer/Dockerfile
    args:
      VARIANT: "3"
      NODE_VERSION: "none"
  volumes:
    - ..:/workspace:cached
  command: ["/bin/bash", "/workspace/entrypoint.sh", "sleep", "infinity"]
  network_mode: service:db
